// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtoGardenEF;

namespace ProtoGardenEF.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20190502091505_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3");

            modelBuilder.Entity("Models.Flower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Color");

                    b.Property<bool>("IsBlooming");

                    b.Property<int?>("NumPetals");

                    b.Property<string>("Smell");

                    b.HasKey("Id");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("Models.Fountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("LastRun");

                    b.Property<TimeSpan?>("RunFor");

                    b.Property<byte[]>("SerialNr");

                    b.HasKey("Id");

                    b.ToTable("Fountains");
                });

            modelBuilder.Entity("Models.Fruit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("NumSeeds");

                    b.Property<int>("Taste");

                    b.Property<long?>("TreeId");

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FountainId");

                    b.HasKey("Id");

                    b.HasIndex("FountainId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("Models.Tree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<int?>("GardenId");

                    b.Property<float>("Height");

                    b.HasKey("Id");

                    b.HasIndex("GardenId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("Models.Fruit", b =>
                {
                    b.HasOne("Models.Tree", null)
                        .WithMany("Fruits")
                        .HasForeignKey("TreeId");
                });

            modelBuilder.Entity("Models.Garden", b =>
                {
                    b.HasOne("Models.Fountain", "Fountain")
                        .WithMany()
                        .HasForeignKey("FountainId");
                });

            modelBuilder.Entity("Models.Tree", b =>
                {
                    b.HasOne("Models.Garden", null)
                        .WithMany("Trees")
                        .HasForeignKey("GardenId");
                });
#pragma warning restore 612, 618
        }
    }
}
